version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.14.1
    environment:
      - CHROME_APP_ID: jfkamlikjbpcgjcdicpjaofammhfgjjh
      - FF_APP_ID: '{8e1ef2d7-d78f-47f9-9b69-c2806eb534fc}'
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: sudo npm i -g web-ext
      - run:
          name: "Package Extension"
          command: git archive -o package.zip HEAD:src
      - run:
          name: "Upload & Publish extension to the Google Chrome Store"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CHROME_CLIENT_ID}&client_secret=${CHROME_CLIENT_SECRET}&refresh_token=${CHROME_REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
              curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T package.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${CHROME_APP_ID}"
              curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${CHROME_APP_ID}/publish"
            fi
      - run:
          name: "Sign & Upload Firefox Addon"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cd src
              web-ext sign --id={FF_APP_ID} --api-key="${FF_JWT_ISSUER}" --api-secret="${FF_JWT_SECRET}"
            fi
